### ISSUE TITLE
🐞 The value of "process.env.NODE_ENV" is always "production"

### ISSUE THREAD

**Issue by caoxiemeihao** [caoxiemeihao/vite-react-electron#14]
## Appearance

In the first line of the "watch. MJS" file, I specified `process.env.NODE_ENV = 'development'`

https://github.com/caoxiemeihao/vite-react-electron/blob/e4087edffe9ec51124e3753228dda6f224a6f484/scripts/watch.mjs#L1

---

But in the `vite.config.mjs` file, I always get "production".

https://github.com/caoxiemeihao/vite-react-electron/blob/e4087edffe9ec51124e3753228dda6f224a6f484/scripts/vite.config.mjs#L8

**Comment by caoxiemeihao** [comment]
In vite source code, my found blow code.

https://github.com/vitejs/vite/blob/5306234aad7e7432fb55c6033a63c6cf74493c3f/packages/vite/src/node/plugins/define.ts#L43

```ts
function generatePattern(
  ssr: boolean
): [Record<string, string | undefined>, RegExp] {
  const processEnv: Record<string, string> = {}
  if (!ssr || config.ssr?.target === 'webworker') {
    Object.assign(processEnv, {
      'process.env.': `({}).`,
      'global.process.env.': `({}).`,
      'globalThis.process.env.': `({}).`
    })
  }

  const replacements: Record<string, string> = {
    ...processNodeEnv,
    ...userDefine,
    ...importMetaKeys,
    ...processEnv
  }

  const pattern = new RegExp(
    // Do not allow preceding '.', but do allow preceding '...' for spread operations
    '(?<!(?<!\\.\\.)\\.)\\b(' +
      Object.keys(replacements)
        .map((str) => {
          return str.replace(/[-[\]/{}()*+?.\\^$|]/g, '\\$&')
        })
        .join('|') +
      // prevent trailing assignments
      ')\\b(?!\\s*?=[^=])',
    'g'
  )

  return [replacements, pattern]
}
```

I want to commit a "PR" to help fix this BUG 🐞

@PAXANDDOS My brother, what do you think that 😄

**Comment by caoxiemeihao** [comment]
I read the source code of "vite" about "build" carefully again.  

I can only set "process.env.NODE_ENV" in "vite.config.mjs" through "mode" instead of "process.env.NODE_ENV" in "watch.mjs". 😅  

https://github.com/vitejs/vite/blob/5306234aad7e7432fb55c6033a63c6cf74493c3f/packages/vite/src/node/build.ts#L367

```js
const config = await resolveConfig(inlineConfig, 'build', 'production')
```

https://github.com/vitejs/vite/blob/5306234aad7e7432fb55c6033a63c6cf74493c3f/packages/vite/src/node/config.ts#L289

```js
if (mode === 'production') {
  process.env.NODE_ENV = 'production'
}
```

**Comment by PAXANDDOS** [comment]
Hey! Can only say that this bug is pretty strange, but I might know why is that happening. 

In my project, which is based on your boilerplate, I used `process.env.MODE` instead of your `process.env.NODE_ENV` because I couldn't get its value in the Main process. And now I can assume that vite sets the` NODE_ENV` value to `production` in all cases.
I attached a screenshot where you can see a log of my `process.env` inside the `vite.config.mjs`, note that I don't set or use `NODE_ENV` anywhere in the project, but it still exists with the `production` value.
![image](https://user-images.githubusercontent.com/40315177/152782164-bac59cc6-7978-43cf-9901-98d509150366.png)


As a workaround, I would suggest renaming `NODE_ENV` to `MODE` aswell.

**Comment by caoxiemeihao** [comment]
Ha-ha! 😄  
The problem is when the template design without considering.  
Thank you for your participation. 👍  

Let me think about how to use `NODE_ENV` more natural.  
The original purpose is to use `process.env.NODE_ENV" in "watch.mjs" correctly anywhere.

**Comment by caoxiemeihao** [comment]
@PAXANDDOS Hey! My Brother.

There are actually two problems.  

1. The first problem has been solved by refactoring. 😅  

2. The second problem is how to use `process.env.NODE_ENV` in Main-process or Preload-script.  

https://github.com/caoxiemeihao/vite-react-electron/blob/2fed75baf0bee4669c414fb0c1bf549faaac5494/packages/main/index.ts#L30

```js
// Use process.env['VITE_DEV_SERVER_HOST'] instead process.env.VITE_DEV_SERVER_HOST
const url = `http://${process.env['VITE_DEV_SERVER_HOST']}:${process.env['VITE_DEV_SERVER_PORT']}`
```

**Comment by PAXANDDOS** [comment]
> ```js
> // Use process.env['VITE_DEV_SERVER_HOST'] instead process.env.VITE_DEV_SERVER_HOST
> const url = `http://${process.env['VITE_DEV_SERVER_HOST']}:${process.env['VITE_DEV_SERVER_PORT']}`
> ```
Yeah, that's pretty strange 😕 I know that some weirdly-typed variables can only be read with `['name']` but that should not be the case...
Anyways I've tested it after your commits and everything works just great! 😄 Also looks better too. Placing separate configs is a good idea.  And I can notice you renamed the `src` folder to `packages` as well😃

**Comment by caoxiemeihao** [comment]
@PAXANDDOS Hey! My br.  
How are you going now.  
I sympathize with you now.  
I wish peace comes at an early date.  🌱

**Comment by PAXANDDOS** [comment]
> @PAXANDDOS Hey! My br. How are you going now. I sympathize with you now. I wish peace comes at an early date. 🌱

Hi! Can't say I'm doing well, no one does... I will never forget that day when I woke up at 5 AM because of explosions. I live in Kharkiv, the city which is being destroyed the most. I got lucky to move away on the first day but forgot to take a lot of stuff, including food, not taking food was the biggest mistake. I'm safe now, but periodically have to go to the shelter because of new explosions around. I'm still not far from the city, now I live in a small town in the city region. Got good internet here, enough water and some food. I really hope all of this ends soon, in any case, my city is already in ruins 😢 
Thank you for caring bro ❤️ Appreciate it

**Comment by caoxiemeihao** [comment]
人没事就好，平安是福！  
If there anything I can do to help, you can directly tell me.
