### ISSUE TITLE
eslint

### ISSUE THREAD

**Issue by gwendalF** [caoxiemeihao/vite-react-electron#16]
Hello and thank you for your template.
How can I setup eslint for this project? I have a eslintrc.json file but it does not seem to lint my files properly

**Comment by PAXANDDOS** [comment]
Hello! Setting up ESLint should be easy.

First of all, you can check [one of my projects](https://github.com/PAXANDDOS/lucast-electron) as an example, it's built using this template and already has eslint enabled and working, but I'll try to go step-by-step and explain:

It would be good if you used eslint extension, it's free and can be downloaded in Visual Studio Code or whatever editor you're using.
1. Download ESLint dependency and needed plugins, for this case we can go: `npm i -D eslint eslint-plugin-react eslint-plugin-react-hooks` but you can add any plugin you want. In my project I also used `@typescript-eslint/eslint-plugin` and `@typescript-eslint/parser`
2. Create `.eslintrc.json` files both in the root and in the `src/renderer` directories.
3. [Example configuration](https://github.com/PAXANDDOS/lucast-electron/blob/fab5cdad7f5f483dd7c80410afe46caaf84e02d2/.eslintrc.json) for the `.eslintrc.json` at the root directory.
4. [Example configuration](https://github.com/PAXANDDOS/lucast-electron/blob/fab5cdad7f5f483dd7c80410afe46caaf84e02d2/packages/renderer/.eslintrc.json) for the `.eslintrc.json` at the `src/renderer` directory.

I guess that's all that needed to get your ESLint to work. Sorry for possible mistakes, was typing from my phone 😅

**Comment by gwendalF** [comment]
Thanks, I will definetly check your project. What's the difference between the two eslint config? Or why two are needed. The Root eslint still apply on the renderer folder or not?

**Comment by PAXANDDOS** [comment]
> Thanks, I will definetly check your project. What's the difference between the two eslint config? Or why two are needed. The Root eslint still apply on the renderer folder or not?

Two configs are needed to separate renderer from the project. Root eslintrc has configuration that is used globally, verdions, parsers, rules, also it's where typescript plugin connected because you use typescript all over the project.
Eslintrc in the renderer directory has settings and plugins for React, because renderer is the only place where you use it.
Yes, eslintrc at the root still applies to the renderer, so I guess you all of your configurations in the single config at the root, but I personally would not recommend that.
